# This kustomization.yaml is not intended to be run by itself since it
# depends on a service name and namespace that are not defined in this package.
# It should be run by building one of the directories in config/context.
resources:
- bases/greymatter.io_meshes.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
- patches/webhook_in_meshes.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# The following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
