# Specifies the namespace for all namespaced resources.
namespace: gm-operator

# Adds a prefix to all resources.
# Note that this prefix should match the prefix of the namespace field above.
namePrefix: gm-

# Labels to add to all resources and selectors.
# commonLabels:
#  someName: someValue

bases:
- crd
- deployment
- rbac
- webhook

patchesStrategicMerge:
- deployment_config_patch.yaml
- deployment_webhook_patch.yaml
