steps:
  - label: ":shipit: build and release"
    commands: 
      - ./scripts/cibuild test
      - ./scripts/cibuild build
      - ./scripts/cibuild release
    retry:
      automatic:
        - exit_status: "*"
          limit: 2
    agents:
      container_image: ubuntu-2110-ci
