# This kustomization should not be run manually using kustomize.
# It patches the referenced kubernetes package by adding placeholders
# for values which will be injected by code that uses the functions
# exported in ../../config.go.

bases:
- ../kubernetes

resources:
- resources.yaml

patchesStrategicMerge:
- patches.yaml
