apiVersion: v1
kind: ConfigMap
metadata:
  name: gm-manager-config
  namespace: gm-operator
data:
  bootstrap_config.yaml: |
    imagePullSecretName: gm-docker-secret
    disableWebhookCertGeneration: {{ .DisableWebhookCertGeneration }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gm-controller-manager
  namespace: gm-operator
spec:
  template:
    spec:
      containers:
      - name: manager
        image: "{{ .DockerImageURL }}"
        resources:
          limits:
            cpu: "{{ .ResourceLimitsCPU }}"
            memory: "{{ .ResourceLimitsMemory }}"
          requests:
            cpu: "{{ .ResourceRequestsCPU }}"
            memory: "{{ .ResourceRequestsMemory }}"
